---
- name: configure apache2
  hosts: all
  tasks:
   - name: call child playbook
     include: "{{item}}"
     with_items:
      - install.yml
      - edit_index.yml
      - restart.yml
      - check_url_response.yml
...        

