---
- name: implementing loops
  hosts: all
  tasks:
   - name: install software
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: git,b: latest,c: yes}
      - {a: maven,b: absent,c: no}
      - {a: openjdk-8-jdk,b: absent,c: no}  
...        
