---
- name: implementing tags
  hosts: all
  tasks:
   - name: install tree
     apt:
      name: tree
      state: present
     tags: tree_installation
   - name: create user
     user:
      name: pinky
      password: Arjun62@
     tags: user_creation
   - name: copy/etc/passwd file
     copy:
      src: /etc/passwd
      dest: /tmp
...      
