---
- name: install firewalld using host sope variable
  hosts: webserver
  tasks:
   - name: install firewalld
     apt: 
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...      
