---
- name: setup required softwres for ci-cd
  hosts: all
  tasks:
   - name: install softwares
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items: 
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
      - {a: tomcat9,b: no}
      - {a: tomcat9-admin,b: no}
- name: continuous download and continuos build
  hosts: prodserver
  tasks: 
   - name: download development code
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: /tmp/mygit
   - name: build code and create an artifact
     shell: cd /tmp/mygit;mvn package
   - name: fetch arifact prodserver to controller
     fetch:
      src: /tmp/mygit/webapp/target/webapp.war
      dest: /tmp
- name: continuous deployment and continuous testing
  hosts: qaserver
  tasks:
   - name: deploy artifact into tomcat on qaserver
     copy:
      src: /tmp/172.31.1.110/tmp/mygit/webapp/target/webapp.war
      dest: var/lib/tomcat9/webapps/qaapp.war
   - name: download selenium scripts
     git: 
      repo: https://github.com/intelliqittrainings/FunctionalTesting.git
      dest: /tmp/test-git
   - name: execute the selenium scripts 
     shell: java -jar /tmp/test-git/testing.jar
- name: continuous delivery
  hosts: prodserver
  tasks: 
   - name: copy artifact on prod server
     copy:
      src: /tmp/172.31.1.110/tmp/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/prodserver
...     
